name: ci

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:

  lint_and_test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6
      - name: Run lint
        run: |
          make lint
        env:
          FIX: 0
          UV_PYTHON: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          make test
        env:
          UV_PYTHON: ${{ matrix.python-version }}
      - name: Make documentation
        if: matrix.python-version == '3.12'
        run: |
          make doc
      - name: Check modified files
        if: matrix.python-version == '3.12'
        run: |
          make no-dirty
      - name: Clean
        if: matrix.python-version == '3.12'
        run: |
          make clean
      - name: Check modified files (after clean)
        if: matrix.python-version == '3.12'
        run: |
          make no-dirty

  mergify-ci-status: # this is a special job for mergify
    runs-on: ubuntu-24.04
    needs: "lint_and_test"
    steps:
      - name: Status
        run: |
          echo "OK"

  publish_pypi:
    runs-on: ubuntu-24.04
    needs: lint_and_test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6
      - name: Publish on Pypi
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's|refs/tags/v||')
          echo "VERSION: $VERSION"
          uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version "$VERSION"
          uv build
          uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
